config/routes.rb
Insource::Application.routes.draw do

  root :to => 'static#home'
  
  match 'about' => 'static#about'
  match 'contact' => 'static#contact'
  match 'products' => 'static#products'
  match 'request' => 'static#request'
  match 'request_thanks' => 'static#request_thanks'
  match 'newsletter_signup' => 'static#newsletter_signup'
  match 'newsletter_signup_thanks' => 'static#newsletter_signup_thanks'
  match 'newsletter_email_thanks' => 'static#newsletter_email_thanks'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :ensure_domain if !Rails.env.development?

  APP_DOMAIN = 'www.insource.it'

  def ensure_domain
    if request.env['HTTP_HOST'] != APP_DOMAIN
      # HTTP 301 is a "permanent" redirect
      redirect_to "http://#{APP_DOMAIN}", :status => 301
    end
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def home
    @title = "Kansas City Small Business IT Support Services"
  end
  
  def contact
    @title = "IT Experts that fix problems fast"
  end
  
  def products
    @title = "Flexible business computer tech support solutions"
  end
  
  def about
    @title = "Small Business IT Experts"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_footer.html.erb
<footer class=footer>
	<div class=top>
		<div class=container>
			<div class=row>
				<div class=span5>
					<h3>Contact information</h3>
					<%= render 'partials/address' %>
				</div>
				<div class=span7>
					<h3>Sign up for the newsletter!</h3>
					<p>Want some easy to use IT tips? Get them here!</p>
					<form class="form-horizontal">
						<div class="control-group">
							<div class="input-append input-prepend">
								<span class=add-on>@</span><input class=span4 type=text size=16><button class=btn type=button>sign up</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class=bottom>
		<div class=container>
			<div class=row>
				<div class="span12">
					<p>&copy; <a href="http://databasically.com">Databasically</a> 2011-2012 all rights reserved - <a href="#">Terms of Service</a></p>
				</div>
			</div>
		</div>
	</div>
	<script type="text/javascript">
	
	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-36784533-1']);
	  _gaq.push(['_trackPageview']);
	
	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	
	</script>
</footer>

app/views/layouts/_header.html.erb
<header class="container header">
	<div class=row>
		<!-- Zhe Logo & name -->
		<div class=span4>
			<h1>
				<%= image_tag "insource-logo.png", :title => "Insource IT" %><br /><small>A service of Databasically</small>
			</h1>
		</div>
		<!-- Menu & Search -->
		<nav class=span8>
			<ul class="nav nav-pills pull-right">
				<li<%= %q( class="active").html_safe if current_page?(root_path) %>><%= link_to "Home", root_path %></li>
				<li<%= %q( class="active").html_safe if current_page?(products_path) %>><%= link_to "Services", products_path %></li>
				<li<%= %q( class="active").html_safe if current_page?(about_path) %>><%= link_to "About us", about_path %></li>
				<li<%= %q( class="active").html_safe if current_page?(contact_path) %>><%= link_to "Contact", contact_path %></li>
			</ul>
		</nav>
		<div class="pull-right">
			<h2><small style="font-size: 1em;">Call us: (913) 562-6666</small></h2>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<html lang="en">
	<head>
	  <title><%= @title %> by Insource IT</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= stylesheet_link_tag "bootstrap.min" %>
	  <%= stylesheet_link_tag "lightbox" %>
	  <%= stylesheet_link_tag "style" %>

	  <%= csrf_meta_tags %>
	  <!-- Data about Data, so meta -->
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta name="description" content="">
		<meta name="viewport" content="width=device-width">
	  <meta name="google-site-verification" content="ZupYjJEEm1Z2T3p9Y57uyhOf1dmVYydMK-zfyWIX_fI" />

		<!-- Zhe fonts und styles -->
		<link href="http://fonts.googleapis.com/css?family=Nobile" rel="stylesheet" type="text/css">
		<link href="http://fonts.googleapis.com/css?family=Ubuntu:bold" rel="stylesheet" type="text/css">

		<!-- Le Favicon and zhe lame apple stuffz -->
		<%= favicon_link_tag 'favicon.ico' %>
		<link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon-precomposed.png">

		<%=javascript_include_tag "libs/modernizr-2.5.3.min" %>
	</head>
<body>
	<!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
	<%= render 'layouts/header' %>
	<%= yield %>
	<%= render 'layouts/footer' %>

	<!-- JS & bottom like zhe pro's -->
	<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" %>
	<%= javascript_include_tag "libs/bootstrap.min" %>
	<%= javascript_include_tag "libs/lightbox" %>
	<%= javascript_include_tag "plugins" %>

</body>
</html>

app/views/partials/_address.html.erb
<p>
	Insource IT<br>
	14539 West 96th Terrace<br>
	Lenexa, KS 66215<br>
	phone: (913) 562-6666<br>
	email: contact@insource.it
</p>